# 新增规格单位价格字段
ALTER TABLE commodity_price ADD STANDARD_PRICE BIGINT(18) NULL COMMENT '规格单位价格, 单位分';
ALTER TABLE commodity_price
  MODIFY COLUMN TIME DATETIME COMMENT '时间' AFTER STANDARD_PRICE;

ALTER TABLE commodity_price_history ADD STANDARD_PRICE BIGINT(18) NULL COMMENT '规格单位价格, 单位分';
ALTER TABLE commodity_price_history
  MODIFY COLUMN TIME DATETIME COMMENT '时间' AFTER STANDARD_PRICE;


ALTER TABLE trade_order ADD COMMODITY_STANDARD_QUANTITY DECIMAL(20) NULL COMMENT '商品规格单位数量';
ALTER TABLE trade_order ADD COMMODITY_STANDARD_PRICE BIGINT(18) NULL COMMENT '商品规格单位单价 分为单位';
ALTER TABLE trade_order
  MODIFY COLUMN COMMODITY_STANDARD_QUANTITY DECIMAL(20) COMMENT '商品规格单位数量' AFTER COMMODITY_UNIT_PRICE,
  MODIFY COLUMN COMMODITY_STANDARD_PRICE BIGINT(18) COMMENT '商品规格单位单价 分为单位' AFTER COMMODITY_STANDARD_QUANTITY;